Cost-based rate limiting
scale-tone/ThrottlingTroll pull request #13
Opened 2023-10-29 21:44 UTC by scale-tone

Adds a `ThrottlingTrollRule.CostExtractor` routine, which can be provided to customize the cost (weight) of each particular request.
The default cost is 1, but now it is possible to have more and less 'expensive' requests and 'charge' the client accordingly.

2023-10-31 18:08 UTC, bahmad12 commented on ThrottlingTroll.Core/ThrottlingTrollHandler.cs
> +            this._troll = new ThrottlingTroll(log, counterStore ?? new MemoryCacheCounterStore(), async () => config, identityIdExtractor, null);
Should this be costExtractor instead of null

2023-10-31 18:09 UTC, bahmad12 commented on ThrottlingTroll.Core/ThrottlingTrollHandler.cs
do we need to add Func<IHttpRequestProxy, long> _costExtractor?

2023-10-31 18:13 UTC, bahmad12 commented on tests/ThrottlingTroll.AspNet.Tests/ThrottlingTrollMiddlewareTests.cs
> +            public override Task DecrementAsync(string limitKey, long count, ICounterStore store)
id it cost instead of count?

2023-10-31 18:15 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
typo 1L --> 1

2023-10-31 18:15 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
typo 1L --> 1

2023-10-31 18:15 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
typo 1L --> 1

2023-10-31 18:15 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
typo 1L --> 1

2023-10-31 18:15 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
typo 1L --> 1

2023-10-31 18:16 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
typo 1L --> 1

2023-10-31 18:16 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
typo 1L --> 1

2023-10-31 18:16 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
typo 1L --> 1

2023-10-31 18:17 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
typo? 2L -->2

2023-10-31 18:18 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
typo? 2L -->2

2023-10-31 18:18 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
typo? 2L -->2

2023-10-31 18:18 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
typo? 2L -->2

2023-10-31 18:18 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
typo? 2L -->2

2023-10-31 18:18 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
typo? 2L -->2

2023-10-31 18:19 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
typo? 2L -->2

2023-10-31 18:19 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
typo? 2L -->2

2023-10-31 18:21 UTC, bahmad12 commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
couple of typo's commented in here

2023-10-31 18:22 UTC, bahmad12 requested changes
looks good only couple of typos

2023-11-02 11:11 UTC, scale-tone commented on ThrottlingTroll.Core/ThrottlingTrollHandler.cs
> +            this._troll = new ThrottlingTroll(log, counterStore ?? new MemoryCacheCounterStore(), async () => config, identityIdExtractor, null);
This ctor was not intended for that, but to make everything completely square let's indeed add another ctor, with costExtractor param.

2023-11-02 11:16 UTC, scale-tone commented on ThrottlingTroll.Core/ThrottlingTrollHandler.cs
Not here. We already have it in ThrottlingTroll (an instance of which is aggregated by this class).

2023-11-02 11:21 UTC, scale-tone commented on tests/ThrottlingTroll.AspNet.Tests/ThrottlingTrollMiddlewareTests.cs
> +            public override Task DecrementAsync(string limitKey, long count, ICounterStore store)
Indeed, thanks

2023-11-02 11:24 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
That param is of type `long`, so I prefer to make it explicit. Rather I'd do the same for the last param here.

2023-11-02 11:25 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
That param is of type long, so I prefer to make it explicit. Rather I'd do the same for the last param here.

2023-11-02 11:25 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
That param is of type long, so I prefer to make it explicit. Rather I'd do the same for the last param here.

2023-11-02 11:26 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
That param is of type long, so I prefer to make it explicit. Rather I'd do the same for the last param here.

2023-11-02 11:26 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
That param is of type long, so I prefer to make it explicit. Rather I'd do the same for the last param here.

2023-11-02 11:26 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
That param is of type long, so I prefer to make it explicit. Rather I'd do the same for the last param here.

2023-11-02 11:27 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
That param is of type long, so I prefer to make it explicit. Rather I'd do the same for the last param here.

2023-11-02 11:27 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
> +            .Setup(s => s.IncrementAndGetAsync(It.IsAny<string>(), 1L, It.IsAny<DateTimeOffset>(), 1))
That param is of type long, so I prefer to make it explicit. Rather I'd do the same for the last param here.

2023-11-02 11:27 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
That param is of type long, so I prefer to make it explicit. Rather I'd do the same for the last param here.

2023-11-02 11:28 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
That param is of type long, so I prefer to make it explicit.

2023-11-02 11:28 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
That param is of type long, so I prefer to make it explicit.

2023-11-02 11:28 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
That param is of type long, so I prefer to make it explicit.

2023-11-02 11:29 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
That param is of type long, so I prefer to make it explicit.

2023-11-02 11:29 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
That param is of type long, so I prefer to make it explicit.

2023-11-02 11:29 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
That param is of type long, so I prefer to make it explicit.

2023-11-02 11:29 UTC, scale-tone commented on tests/ThrottlingTroll.Tests/ThrottlingTrollHandlerTests.cs
>              .Returns(Task.FromResult(2L));
That param is of type long, so I prefer to make it explicit.

2023-11-02 16:07 UTC, merged